### ISSUE TITLE
outdated auth0 lock

### ISSUE THREAD

**Issue by vmartynets** [atomrc/cyclejs-auth0#2]
Up-to-date version is 10.0, when used in this package is [9.0.0](https://github.com/atomrc/cyclejs-auth0/blob/master/package.json#L28).

**Comment by atomrc** [comment]
Thanks for reporting. 

I am not yet sure what is the best way to do that for a lib. It's either:
- I am less restrictive in my dependencies declaration (eg. `"auth0-lock": "*"` or `">=9.0.0"`);
- or I force the 10th version (eg. `"auth0-lock": "^10.0.0"`);
- any other way I might not know about?

I the first case, the end user can install whatever version he likes, the `cyclejs-auth0` will work with this version (considering there are no breaking changes in future versions).

In the second case, I force the use of version `^10.0.0`, and when there is an new version of `auth0-lock`, I should create a new version of `cyclejs-auth0`.

I guess the scenario where I enforce the version might be the best. But I am still not 100% convinced, so if you have any suggestion, I'd be happy to hear them :)

**Comment by atomrc** [comment]
Ok so upgrading to auth0-lock v10 was a little more work than I though, but it's finally done :)

You can upgrade to v2.0.0 to use the auth0-lock v10
