### ISSUE TITLE
No token$ item when page refresh

### ISSUE THREAD

**Issue by SteveALee** [atomrc/cyclejs-auth0#7]
The token$ gets an event when the user authenticates with the lock but not when the page refreshes and the user stays logged in.

This may or may not be correct I just thought I'd point out there is no event to use on refresh. Obviously we can look in local storage but it's better to have some sort of trigger

**Comment by atomrc** [comment]
Oh really! I think you might have a problem elsewhere because storing the token in localStorage and sending it when subscribed is the whole point of the ‘token$‘ steam.

**Comment by SteveALee** [comment]
I think that in the case the lock screen does not show you never get the event you use to push to token$

**Comment by atomrc** [comment]
No it should work even if the lock doesn't show up https://github.com/atomrc/cyclejs-auth0/blob/master/src/makeAuth0Driver.js#L102

**Comment by SteveALee** [comment]
Ah, yes. Nice. Sorry. So something else as you say.

Am going completely auth blind with auwful Picasa api :(
